(function(g){var k=window.AmazonUIPageJS||window.P,m=k._namespace||k.attributeErrors,f=m?m("NileInlineCustomerExperienceWidgetCommonAssets",""):k;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,k,m){g.now("nile-inline-error-chunk-handler").execute(function(f){f||g.when("A","nile-inline-loader-utils","nile-inline-element-prefix-utils","ready").register("nile-inline-error-chunk-handler",function(d,b,a){return{handleChunk:function(e,g){var c=a.prefixed("nile-inline-hidden");
if(d.$(a.prefixedId("nile-inline-answer-generic-error")).hasClass(c)){b.hideLoader();b.hideTrailingLoader();var h=a.prefixedId("nile-inline-answer-container");d.$(h).removeClass(c);h=a.prefixedId("nile-inline-answer-text-container-error");d.$(h).removeClass(c);d.$(h).addClass(a.prefixed("nile-inline-text-container-collapsed-error"));var f=a.prefixedId("nile-inline-ai-generated-label");"sensitive_chunk"===g?d.$(f).addClass(c):d.$(f).removeClass(c);d.$(h).html(e)}}}})});g.now("nile-inline-feedback-chunk-handler").execute(function(f){f||
g.when("A","nile-inline-element-prefix-utils","nile-inline-feedback-actions","ready").register("nile-inline-feedback-chunk-handler",function(d,b,a){return{handleChunk:function(e){e=d.$(e);d.$(b.prefixedId("nile-inline-feedback-container")).html(e);a.showFeedback();return e}}})});g.now("nice-srp-utils").execute(function(f){f||g.when("A","ready").register("nice-srp-utils",function(d){function b(l,a){l=(l||"").split(".").map(Number);for(a=(a||"").split(".").map(Number);l.length<a.length;)l.push(0);for(;a.length<
l.length;)a.push(0);for(var c=0;c<l.length;++c)if(l[c]!==a[c])return l[c]>a[c]?1:-1;return 0}function a(){var a=c();return"Amazon"===a.name||"Amazon.com"===a.name}var e=d.$,f=[],c=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*amzn-app-id\s*=\s*([^\s;]+)/);c=c?c[1].split("/"):[];var b=/(?:^|;)\s*micron\s*=\s*1\s*(?:$|;)/.test(document.cookie);a={name:c[0],version:c[1],isMicron:b}}return a}}(),h=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*session-id\s*=\s*([^\s;]+)/);
c&&(a=c[1])}return a}}(),g=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*amzn-app-ctxt\s*=\s*\d\.\d?\s*([^\s;]+)/);if(c)try{a=JSON.parse(decodeURIComponent(c[1]))}catch(n){}}return a}}();return{getAppInfo:c,getAppSessionId:h,getAppContext:g,makeIdempotent:function(a){var c=!1;return function(){c||(a.apply(this,arguments),c=!0)}},makeRateLimited:function(a,c){var b=!1,d=e.extend(!0,{},{minPeriodInMilliseconds:2E3},c);return function(){b||a.apply(this,arguments);b=
!0;setTimeout(function(){b=!1},d.minPeriodInMilliseconds)}},idempotentDeclarative:function(a,c,b){function e(a,c,b){var e;d.declarative(a,c,function(a){e===m&&(e=a.type);a.type===e&&b(a)})}var h=a+c;f[h]||("click touchstart"===c||"touchstart click"===c?e(a,c,b):d.declarative(a,c,b),f[h]=!0)},goToUrl:function(a){k.location.href=a},isMshop:a,isAppXSupported:function(){var e=c();return a()&&e.version&&!e.isMicron?Number(e.version.split(".")[0])%2?0<=b(e.version,"15.11"):0<=b(e.version,"20.8"):!1},truncateURIComponent:function(a,
c,b){if(!a||encodeURIComponent(a).length<=c)return a;b=b||"…";c-=encodeURIComponent(b).length;for(var e="",d=0,h=a.length-1;d<=h;){var f=Math.floor((h+d)/2),g=a.slice(0,f);encodeURIComponent(g).length<=c?(e=g,d=f+1):h=f-1}return e+b},decodeHtmlEntities:function(a){var c=document.createElement("textarea");c.innerHTML=a;return c.value}}})});g.now("nile-inline-csm").execute(function(f){f||g.when("A","ready").register("nile-inline-csm",function(){function d(b,a,e){"function"===typeof uet&&(e?uet(b,a,
{wb:1},e):uet(b,a,{wb:1}))}return{recordRequestStart:function(b,a){"string"===typeof b&&b.trim()&&d("bb",b,a)},recordFirstInferenceLatency:function(b){"string"===typeof b&&b.trim()&&(d("be",b),"function"===typeof uex&&uex("ld",b,{wb:1}))},recordCsmCount:function(b){ue.count(b,1)}}})});g.now("nile-inline-csrf").execute(function(f){f||g.when("A","ready").register("nile-inline-csrf",function(d){return{getRawCsrfToken:function(b){return d.$(b).find("input[name\x3danti-csrftoken-a2z]").val()}}})});g.now("nile-inline-element-prefix-utils").execute(function(f){f||
g.when("ready").register("nile-inline-element-prefix-utils",function(){var d="";return{setupElementPrefix:function(b){d=b+"-"},prefixed:function(b){return d+b},prefixedId:function(b){return"#"+d+b}}})});g.now("nile-inline-loader-utils").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils","ready").register("nile-inline-loader-utils",function(d,b){return{showTrailingLoader:function(){var a=b.prefixed("nile-inline-hidden");var e=b.prefixedId("nile-inline-feedback-container");(e=!d.$(e).hasClass(a)&&
0<d.$(e).children().length)||(e=b.prefixedId("nile-inline-answer-generic-error"),e=!d.$(e).hasClass(a)&&0<d.$(e).children().length);e||(e=b.prefixedId("nile-inline-answer-text-container-error"),e=!d.$(e).hasClass(a)&&0<d.$(e).children().length);e||d.$(b.prefixedId("nile-trailing-loader")).removeClass(a)},hideTrailingLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-trailing-loader")).addClass(a)},showLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-inline-data-container")).removeClass(a);
d.$(b.prefixedId("nile-inline-loader-spinner")).removeClass(a)},hideLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-inline-loader-spinner")).addClass(a);d.$(b.prefixedId("nile-inline-data-container")).addClass(a)}}})});g.now("nile-inline-state-manager").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils","ready").register("nile-inline-state-manager",function(d,b){function a(){return b.prefixed("nice-state")}return{getState:function(){d.state(a())||
d.state.parse();return d.state(a())},setState:function(b){d.state.replace(a(),b)},extend:function(b){d.state(a(),b)}}})});g.now("nile-inline-uuid-generator").execute(function(f){f||g.when("A","ready").register("nile-inline-uuid-generator",function(d){return{generateUuid:function(){function b(){var a=new Uint32Array(4);k.crypto.getRandomValues(a);var b=-1;return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){b++;var e=a[b>>3]>>b%8*4&15;return("x"===c?e:e&3|8).toString(16)})}function a(){function a(){return Math.floor(65536*
(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}return function(){return"undefined"!=typeof k.crypto&&"undefined"!=typeof k.crypto.getRandomValues?b():a()}}()}})});g.now("nile-inline-event-stream-builder").execute(function(f){f||g.when("A","jQuery","ready").register("nile-inline-event-stream-builder",function(d,b){function a(a){this.url=a;this.eventListeners={};this.connectionSuccessfullyClosedCallback=this.errorCallback=this.httpRequest=m}function e(a){var c=
a.newMessage();return function(b,d){if(0===b.length){if(c.type in a.eventListeners)a.eventListeners[c.type](c);c=a.newMessage()}else if(0<d){var e=b.slice(0,d);b=b.slice(d+(" "===b[d+1]?2:1));switch(e){case "data":c.data=c.data?c.data+"\n"+b:b;break;case "event":c.type=b;break;case "id":c.lastEventId=b;break;case "retry":e=parseInt(b,10),isNaN(e)||(c.retry=e,a.retryCallback(c.retry))}}}}function f(a){var c=0,b=-1,d=!1;return function(e){for(var f=e.length,g=c;c<f;){d&&"\n"===e[c]&&(g=++c);for(var h=
-1;c<f&&-1===h;++c)switch(e[c]){case ":":-1===b&&(b=c-g);break;case "\r":d=!0;h=c;break;case "\n":h=c}if(-1===h)break;a(e.slice(g,h),b);g=c;b=-1}g!==f&&0!==g&&(c=g)}}a.prototype.addEventListener=function(a,b){this.eventListeners[a]=b};a.prototype.setErrorCallback=function(a){this.errorCallback=a};a.prototype.setConnectionSuccessfullyClosedCallback=function(a){this.connectionSuccessfullyClosedCallback=a};a.prototype.newMessage=function(){return{lastEventId:"",type:"",data:""}};a.prototype.isSuccessfulStatusCode=
function(a){return 0===a||200<=a&&300>a};a.prototype.buildRequestStageChangeCallback=function(a){return function(){switch(a.httpRequest.readyState){case XMLHttpRequest.DONE:a.isSuccessfulStatusCode(a.httpRequest.status)?a.connectionSuccessfullyClosedCallback!==m&&a.connectionSuccessfullyClosedCallback():a.errorCallback!==m&&a.errorCallback()}}};a.prototype.buildOnProgressCallback=function(a,b){return function(){b(a.httpRequest.responseText)}};a.prototype.retryCallback=function(a){};a.prototype.startPostStream=
function(a,b,d){var c=f(e(this));this.httpRequest=new XMLHttpRequest;this.httpRequest.onreadystatechange=this.buildRequestStageChangeCallback(this);this.httpRequest.onprogress=this.buildOnProgressCallback(this,c);this.httpRequest.ontimeout=this.errorCallback;this.httpRequest.onerror=this.errorCallback;this.httpRequest.open("POST",this.url,!0);this.httpRequest.timeout=d;this.httpRequest.setRequestHeader("accept","text/event-stream");this.httpRequest.setRequestHeader("Content-Type","application/json");
this.httpRequest.setRequestHeader("anti-csrftoken-a2z",b);this.httpRequest.send(JSON.stringify(a))};a.prototype.close=function(a){this.httpRequest.onerror=function(){};this.httpRequest.abort()};return{buildStreamingEndpointCall:function(b){return new a(b)}}})});g.now("nile-inline-collapse-bottom-sheet").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils").register("nile-inline-collapse-bottom-sheet",function(d,b){return{registerCollapseBottomSheetActions:function(){var a=b.prefixed("nile-inline-widget");
a=d.$("[data-component-type\x3d"+a+"]");if(1===a.length||1===a.parent().length){a=a.parent()[0];var e=!1;(new IntersectionObserver(function(a){e?a[0].isIntersecting?g.when("mash").execute(function(a){a.dispatchEvent({type:"nice:inViewPort"})}):g.when("mash").execute(function(a){a.dispatchEvent({type:"nice:outViewPort"})}):e=!0},{threshold:.05})).observe(a)}}}})})});
/* ******** */
'use strict';(function(d){var k=window.AmazonUIPageJS||window.P,l=k._namespace||k.attributeErrors,b=l?l("NileInlineCustomerExperienceWidgetDPXRexAssets@ask",""):k;b.guardFatal?b.guardFatal(d)(b,window):b.execute(function(){d(b,window)})})(function(d,k,l){d.now("askSearch").execute(function(b){b||d.when("A","jQuery","rufusAskExpander","ready").register("askSearch",function(h,e,a){function b(){d&&d.abort();e(".askAnswerContainer").remove()}var d;return{setupExpander:function(){a.setupDesktopSeeMoreLessToggle();
a.setupMobileExpander()},executeSearch:function(a,g,n){n&&b();a={indicator:e("#ask-only-spinner"),params:{asin:a,query:g,isBlue:n},timeout:1E4,success:function(c){b();e("#ask-answer-container").append(c);c=h.$("#ask-loaded-response-text").text();h.$("#dpx-rex-nile-loading-response").append(c)}};d=h.get("/rufus/web/askSearch",a)},clearSearch:b}})});d.now("rufusAskExpander").execute(function(b){b||d.when("A","jQuery","ready").register("rufusAskExpander",function(b,e){return{setupDesktopSeeMoreLessToggle:function(){e(document).delegate(".askSeeMore",
"click",function(a){e(a.currentTarget).closest(".askExpanderContainer").addClass("askExpanderExpanded");a.preventDefault()});e(document).delegate(".askSeeLess","click",function(a){e(a.currentTarget).parents(".askExpanderContainer").removeClass("askExpanderExpanded");a.preventDefault()})},setupMobileExpander:function(){b.on("a:expander:askMobileLiveSearchResultExpander:toggle:expand",function(a){a=a.expander.$expander;a.find(".askMobileLiveSearchResultHeaderTextExpanded").css("display","block");a.find(".askMobileLiveSearchResultHeaderTextCollapsed").hide()});
b.on("a:expander:askMobileLiveSearchResultExpander:toggle:collapse",function(a){a=a.expander.$expander;a.find(".askMobileLiveSearchResultHeaderTextExpanded").hide();a.find(".askMobileLiveSearchResultHeaderTextCollapsed").css("display","block")})}}})});d.now("askAbstractPostQuestion").execute(function(b){b||d.when("A","ready").register("askAbstractPostQuestion",function(b){var e=b.$,a={postQuestionTextInputSelector:"input",callbacks:{goodQuestion:function(){},badQuestion:function(){},emptyQuestion:function(){}}};
return{setup:function(d,h){var f=e.extend(!0,{},a,h),g=!1;if(f.modalName)b.on("a:popover:beforeShow:"+f.modalName,function(a){g=!1});if(f.bottomSheetName)b.on("a:sheet:beforeShow:"+f.bottomSheetName,function(a){g=!1});b.declarative(d,"click",function(){var a=e(f.postQuestionTextInputSelector).find("input").andSelf().filter("input").val();a||(a=e(f.postQuestionTextInputSelector).find("textarea").andSelf().filter("textarea").val());var c=e(f.formSelector+" .promptPostQuestionTextInput"),b=e(f.modalFormSelector+
" textarea");a=b.length?b.val():c.length?c.val():a;"undefined"===typeof a||a.match(/^\s*$/)?f.callbacks.emptyQuestion():g?f.callbacks.goodQuestion():-1===a.indexOf("?")&&-1===a.indexOf("؟")?(f.callbacks.badQuestion(),g=!0):f.callbacks.goodQuestion()})}}})});d.now("askPostQuestion").execute(function(b){b||d.when("A","askAbstractPostQuestion","nile-inline-csrf","nile-inline-state-manager","ready").register("askPostQuestion",function(b,d,a,k){function e(a){c(".askMobilePostQuestionSuccessContainer").find(".post-success-response").html(a);
g(".askMobilePostQuestionSuccessContainer")}function f(a){if(401===a.status||466===a.status)c(".askMobilePostQuestionFormInBottomSheet").submit();else{a=a.http.responseText;var b=c(".askMobilePostQuestionFailureContainer").find(".failureDefaultMsg");a&&0<a.length?(c(".askMobilePostQuestionFailureContainer").find(".failureResponseMsg").html(a),b.hide()):b.show();g(".askMobilePostQuestionFailureContainer")}}function g(a,b){b=b||c("#ask-mobile-post-question-modal-container");b.children().hide();a=b.find(a);
a.removeClass("aok-hidden");a.show()}function h(d,e,f){var m={};c.each(d.serializeArray(),function(a,b){m[b.name]=b.value});m.askAsin=k.getState().asin;b.post(d.attr("action"),{withCredentials:!0,params:JSON.stringify(m),paramsFormat:"json",headers:{"anti-csrftoken-a2z":a.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),"Content-Type":"application/json"},timeout:1E4,indicator:c(".askMobilePostQuestionSpinner"),success:e,error:f})}var c=b.$,l=null,p=function(a){c("#ask-post-question-text-area").attr("aria-invalid",
"true");".askBadQuestionError"===a?c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description ask-bad-question-error"):".askEmptyQuestionError"===a&&c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description ask-empty-question-error");g(a,c(".askMobilePostQuestionMsgContainer"))},q={postQuestionTextInputSelector:"#ask-mobile-post-question-modal-container .askMobilePostQuestionInput",bottomSheetName:"ask-mobile-post-question-modal",
callbacks:{goodQuestion:function(){c("#ask-post-question-text-area").removeAttr("aria-invalid");c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description");c(".askMobilePostQuestionSubmitButtons").hide();c(".askMobilePostQuestionMsgContainer").children().hide();h(c(".askMobilePostQuestionFormInBottomSheet"),e,f)},badQuestion:function(){p(".askBadQuestionError")},emptyQuestion:function(){p(".askEmptyQuestionError")}}};return{registerDeclarativeActions:function(){var a=
function(){var a=c("*[id*\x3dask-mobile-post-question-modal]");1<a.length&&0<c(".a-sheet-content-container #ask-mobile-post-question-modal").length&&a.each(function(){0>=c(this).closest(".a-sheet-content-container").length&&c(this).remove()})},e=function(b){a();b=c("#dpx-rex-nile-search-text-input").val();if(l!==b){var d=c("#ask-mobile-post-question-modal-container .askMobilePostQuestionInput").find("input").andSelf().filter("input");d&&0!==d.length||(d=c("#ask-mobile-post-question-modal-container .askMobilePostQuestionInput").find("textarea").andSelf().filter("textarea"));
d.val(b);l=b}c(".askMobilePostQuestionMsgContainer").children().hide();g(".askMobilePostQuestionFormInBottomSheet");c(".askMobilePostQuestionSubmitButtons").show()};b.on("a:sheet:beforeShow:ask-mobile-post-question-modal",e);b.on("a:popover:beforeShow:ask-mobile-post-question-modal",e);b.declarative("ask-mobile-post-question-input-keyup","keypress",function(a){a&&a.$event&&13===a.$event.which&&a.$event.preventDefault()});d.setup("ask-mobile-post-question-submit",q)}}})})});
/* ******** */
'use strict';(function(e){var v=window.AmazonUIPageJS||window.P,u=v._namespace||v.attributeErrors,f=u?u("NileInlineCustomerExperienceWidgetDPXRexAssets@rufus",""):v;f.guardFatal?f.guardFatal(e)(f,window):f.execute(function(){e(f,window)})})(function(e,v,u){e.now("nile-inline-answer-chunk-handler").execute(function(f){f||e.when("A","jQuery","a-truncate","nile-inline-html-truncator","nile-inline-loader-utils","dpx-rex-nile-inline-display-utils","ready").register("nile-inline-answer-chunk-handler",function(a,
n,f,h,g,d){function b(a){return a.filter('[id^\x3d"section_groupId_"]').map(function(){return this.id}).get()}function e(a,d){b(d).forEach(function(b){var k=d.filter("#"+b);b=a.find("#"+b);if(b.length){var g=parseInt(b.attr("data-ask-sequenceId")),h=parseInt(k.attr("data-ask-sequenceId"));if(isNaN(g)||isNaN(h)||g<=h)b.html(k.html()),b.attr("data-ask-sequenceId",k.attr("data-ask-sequenceId"))}else a.append(k)})}var r=a.$("#dpx-rex-nile-inline-see-more-outer");return{handleChunk:function(a,b){if("Carousel-related_questions_carousel_horizontal"===
(b&&b.sectionMetadata&&b.sectionMetadata.type?b.sectionMetadata.type:u))return a=n(a),n("#dpx-rex-nile-inline-followon-pills-outside-container").html(a),a;b=a;a=n("#dpx-rex-nile-inline-answer-text-container");if(b=b.trim()){g.hideLoader();d.show("#dpx-rex-nile-inline-answer-container");var l=n(b);b=l[0]&&l[0].dataset.askBlueChunkType?l:n("\x3cdiv/\x3e").append(b);e(a,n(b));h.maybeTruncate(a,r,9)}else a=void 0;return a}}})});e.now("nile-inline-chunk-renderer").execute(function(f){f||e.when("A","nile-inline-answer-chunk-handler",
"nile-inline-error-chunk-handler","nile-inline-feedback-chunk-handler","nile-inline-state-manager","dpx-nile-inline-constants").register("nile-inline-chunk-renderer",function(a,n,f,h,g,d){return{renderChunk:function(a,e){e.beforeChunk(a);if("CONTEXT_CHUNK"===a.type)a=JSON.parse(a.data).requestContext,g.getState()&&a&&g.extend({conversationHistoryId:a.conversationHistoryId,requestId:a.requestId});else if("chunk"===a.type){var b=JSON.parse(a.data),r=b.htmlRenderedChunk;if(r){var q=null;if("text"===
a.lastEventId)q=n.handleChunk(r,b);else if("feedback_chunk"===a.lastEventId)q=h.handleChunk(r);else if("sensitive_chunk"===a.lastEventId||"softlanding_error_chunk"===a.lastEventId||"internal_error_chunk"===a.lastEventId)g.extend({streamingState:d.streamingState.ERROR}),f.handleChunk(r,a.lastEventId);e.afterChunkRender(a,q)}}}}})});e.now("dpx-rex-nile-inline-widget-instrumentation").execute(function(f){f||e.when("A","nice-srp-utils","nile-inline-state-manager","ready").register("dpx-rex-nile-inline-widget-instrumentation",
function(a,n,e){function h(c){var a=Array.from(arguments).slice(1,arguments.length);return function(){for(var m=arguments.length,b=Array(m),d=0;d<m;d++)b[d]=arguments[d];c.apply(void 0,a.concat(b))}}function g(c){c=[c.dataset.blueMetrics,c.dataset.actionId];c=c.filter(function(c){return c!==u&&null!==c&&""!==c});return c.join(":")}function d(c){for(var a=Object.keys(c),b=0;b<a.length;b++){var d=a[b],g=c[d];null===g||g===u?g="":"number"===typeof g&&(g=g.toString());c[d]=g}return c}function b(c,a){var m=
n.getAppInfo(),b=n.getAppContext(),g=e.getState();c=Object.assign({timestamp:t(new Date),producerId:"mshop-nile",metadata:'{"program":"BLUE_DPX"}',isBeta:!1,deviceTypeId:b&&b.di&&b.di.dti||"",directedCustomerId:g.directedCustomerId||"",appVersion:m&&m.version||"",locale:g.locale||"UNKNOWN",marketplaceId:g.marketplaceId||"UNKNOWN",uxSessionId:"",sessionId:n.getAppSessionId()||""},c);"undefined"!==typeof ue&&ue.event(d(c),"mshop-nile",a)}function f(c,a){"CONTEXT_CHUNK"===a.type?c.requestId||(c.requestId=
JSON.parse(a.data).requestContext.requestId,w(c,c.actionId||"ANSWER"),c.searchTrigger!==u&&b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(c.requestStartAt),nileRequestId:c.requestId,clickstreamRequestId:null,eventName:"SEARCH_TRIGGER",eventDetail:c.searchTrigger},"mshop.nile.events.4")):"chunk"===a.type&&O.includes(a.lastEventId)&&c.chunks.addFromEvent(a)}function r(c,a){if(a=a[0])a.isIntersecting||!c.answer.impressingStartAt?c.answer.impressingStartAt=new Date:(c.answer.impressingEndAt=new Date,
0===a.boundingClientRect.width&&0===a.boundingClientRect.height?z(c,"SEARCH_RESULTS_CLEARED"):z(c,"SCROLLED_AWAY"),c.answer.impressingStartAt=null,c.answer.impressingEndAt=null)}function p(c,a){var b=c.luggage,m=b.items[c.key];if(a=a[0])a.isIntersecting?(m.impressingStartAt=new Date,b.visibleElems.add(m.key)):m.impressingStartAt&&(m.impressingEndAt=new Date,m.reason=0===a.boundingClientRect.width&&0===a.boundingClientRect.height?"SEARCH_RESULTS_CLEARED":"SCROLLED_AWAY",A(c),m.impressingStartAt=null,
m.impressingEndAt=null,b.visibleElems.remove(m.key))}function E(c){var a=c.luggage.items[c.key];a.impressingStartAt&&"visible"!==document.visibilityState&&(document.contains(a.elem)&&(a.impressingEndAt=new Date,a.reason="PAGE_HIDDEN",A(c)),document.removeEventListener("visibilitychange",a.pageVisibilityChangeListener))}function l(c){c.answer.impressingStartAt&&"visible"!==document.visibilityState&&(c.answer.impressingEndAt=new Date,z(c,"PAGE_HIDDEN"),c.answer.observer.unobserve(c.answer.elem),document.removeEventListener("visibilitychange",
c.answer.visibilityChangeListener))}function k(c,a,b){b=b.find("[data-blue-metrics]");var m=h(G,c);c.visibilityChangeListenerForLatency=m;document.addEventListener("visibilitychange",c.visibilityChangeListenerForLatency);(m=document.getElementById("dpx-rex-nile-search-text-input"))&&!m.hasAttribute("listenerOnFocus")&&(m.addEventListener("touchend",h(v,c)),m.setAttribute("listenerOnFocus","true"));(m=document.getElementById("dpx-rex-nice-clear-button"))&&!m.hasAttribute("listenerOnErase")&&(m.addEventListener("touchend",
h(T,c)),m.setAttribute("listenerOnErase","true"));x(c);for(m=0;m<b.length;m++){var d=b[m],k=g(d);c.items[k]?(c.items[k].elem&&c.items[k].elem.observer&&c.items[k].elem.observer.disconnect(),c.items[k].elem=d):(c.items[k]={key:k,elem:d,name:d.dataset.blueMetrics,detail:d.dataset.actionId},y(c,a,d.dataset.actionId));d={luggage:c,key:k};k=d;var l=k.luggage.items[k.key];l.elem.observer||(l.elem.observer=new IntersectionObserver(h(p,k),{threshold:.85}),l.elem.observer.observe(l.ghost||l.elem),l.pageVisibilityChangeListener||
(l.pageVisibilityChangeListener=h(E,k),document.addEventListener("visibilitychange",l.pageVisibilityChangeListener)));k=d.luggage.items[d.key];k.elem.clickListener||(k.elem.clickListener=h(U,d),k.elem.addEventListener("click",k.elem.clickListener))}}function x(c){var a=document.getElementById("dpx-rex-nile-search-text-input");a&&!a.hasAttribute("listenerOnErase")&&(a.addEventListener("input",function(){!H&&0<a.value.length?H=!0:H&&0===a.value.length&&(b({schemaId:"mshop.nile.events.4",eventTimeUTC:(new Date).toISOString(),
nileRequestId:C.luggage&&C.luggage.requestId,clickstreamRequestId:null,eventName:"SEARCH_INPUT_ERASE",eventDetail:"CLEAR"},"mshop.nile.events.4"),H=!1)}),a.setAttribute("listenerOnErase","true"))}function D(c,b,d){if("chunk"===b.type&&O.includes(b.lastEventId)){var m=c.chunks.markAsRendered(b);if("text"===b.lastEventId){if(b=document.getElementById("dpx-rex-nile-inline-answer-text-container")){var g=c.answer,e=document.getElementById("ghost");if(!e){var f=document.createElement("div");a.$(f).addClass("nile-inline-ghost");
e=document.createElement("div");e.id="ghost";e.className="ghost-inner-div";a.$(f).append(e);a.$(b).append(f)}g.ghost=e;c.answer.elem=b;y(c,m,"ANSWER");b=c.answer;b.observer||(b.observer=new IntersectionObserver(h(r,c),{threshold:.85}),b.visibilityChangeListener=h(l,c),document.addEventListener("visibilitychange",b.visibilityChangeListener),b.observer.observe(b.ghost||b.elem));k(c,m,d);m=d.find("#nile-category-cards-mobile-carousel");d=d.find("[id^\x3dsection_groupId_related_questions]");I(c,m,"category_list_carousel_horizontal");
I(c,d,"FOLLOW_ON_PILLS_OUTSIDE_SEEMORE")}}else"feedback_chunk"===b.lastEventId&&(y(c,m,"ANSWER_FEEDBACK"),m=d.find("#dpx-rex-nile-thumbs-up")[0],d=d.find("#dpx-rex-nile-thumbs-down")[0],m&&d&&(m.addEventListener("touchend",h(K,c),{once:!0}),d.addEventListener("touchend",h(L,c),{once:!0})))}}function V(c,a){c.chunks.addFromEvent(a)}function M(c,a,d){c.requestEndAt=new Date;a=c.chunks.markAsRendered(a);var m=d[0]&&d[0].matches("[data-blue-request-id]")||d[0]&&d[0].querySelector("[data-blue-request-id]");
m&&(c.requestId=m.dataset.blueRequestId,b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(c.requestStartAt),nileRequestId:c.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE",eventDetail:c.actionId||"default_pills_fetched"},"mshop.nile.events.4"),w(c),k(c,a,d),I(c,d,"DEFAULT_PILLS"))}function K(c,a){Q(c,"THUMBS_UP")}function L(c,a){Q(c,"THUMBS_DOWN")}function I(c,a,b){a&&(a=a.find(".a-carousel-viewport")[0])&&a.addEventListener("scroll",h(B,c,b),{once:!0})}function J(c,a){c.requestEndAt=new Date;
document.removeEventListener("visibilitychange",c.visibilityChangeListenerForLatency)}function G(c){if("visible"!==document.visibilityState&&!c.requestEndAt){c.interruptedAt=new Date;var a=c.flow.toUpperCase(),d=c.chunks.maybeGetLastRendered();b({schemaId:"mshop.nile.latency.6",nileRequestId:c.requestId,elementId:a,seqId:d?d.index+1:0,requestStartTimeUTC:t(c.requestStartAt),renderingStartTimeUTC:"",renderingEndTimeUTC:"",interruptedTimeUTC:t(c.interruptedAt)},"mshop.nile.latency.6");0<Object.keys(c.items).length||
(document.removeEventListener("visibilitychange",c.visibilityChangeListenerForLatency),R(c,"PAGE_HIDDEN"))}}function z(c,a){b({schemaId:"mshop.nile.impressions.1",nileRequestId:c.requestId,elementId:"ANSWER",seqId:0,requestStartTimeUTC:t(c.requestStartAt),impressionStartTimeUTC:t(c.answer.impressingStartAt),impressionEndTimeUTC:t(c.answer.impressingEndAt),impressionEndReason:a},"mshop.nile.impressions.1")}function A(c){var a=c.luggage;c=a.items[c.key];b({schemaId:"mshop.nile.impressions.1",nileRequestId:a.requestId,
elementId:c.detail||c.name,seqId:c.chunkId||0,requestStartTimeUTC:t(a.requestStartAt),impressionStartTimeUTC:t(c.impressingStartAt),impressionEndTimeUTC:t(c.impressingEndAt),impressionEndReason:c.reason},"mshop.nile.impressions.1")}function y(a,d,k){b({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:k,seqId:d.index,requestStartTimeUTC:t(a.requestStartAt),renderingStartTimeUTC:t(d.renderingStartAt),renderingEndTimeUTC:t(d.renderingEndAt),interruptedTimeUTC:""},"mshop.nile.latency.6")}
function w(a,d){b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(a.requestStartAt),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE_BACKEND_API",eventDetail:d},"mshop.nile.events.4")}function Q(a,d){b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"MAIN_FEEDBACK_REQUEST",eventDetail:d},"mshop.nile.events.4")}function U(a){var c=a.luggage.items[a.key];b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),
nileRequestId:a.luggage.requestId,clickstreamRequestId:null,eventName:c.name,eventDetail:c.detail},"mshop.nile.events.4")}function B(a,d){b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"SCROLL_BUTTON_CAROUSEL",eventDetail:d},"mshop.nile.events.4")}function v(a){b({schemaId:"mshop.nile.events.4",eventTimeUTC:(new Date).toISOString(),nileRequestId:C.luggage&&C.luggage.requestId,clickstreamRequestId:null,eventName:"SEARCH_INPUT_FOCUS",
eventDetail:"TOUCH"},"mshop.nile.events.4")}function T(a){b({schemaId:"mshop.nile.events.4",eventTimeUTC:(new Date).toISOString(),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"CLEAR_BUTTON_PRESS",eventDetail:"clear_button_touch"},"mshop.nile.events.4");H=!1}function R(a,d){b({schemaId:"mshop.nile.events.4",eventTimeUTC:t(a.interruptedAt),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"CONVERSATION_ABANDONMENT",eventDetail:d},"mshop.nile.events.4")}function N(){var a=
document.getElementById("dpx-rex-nile-search-text-input");return a&&a.value||""}function S(){if("visible"!==document.visibilityState){var a=N();""!==a&&a!==C.textInputValue&&(R({interruptedAt:new Date},"QUERY_NOT_SUBMITTED"),document.removeEventListener("visibilitychange",S))}}function t(a){return a instanceof Date?a.toISOString():""}function W(a){a=(a=(a=a&&a.event&&a.event.$event&&a.event.$event.target)&&a.closest("[data-blue-metrics]"))&&a.dataset&&a.dataset.actionId;return/^[a-z][a-z0-9]*(?:_[a-z0-9]+)*_\d_\d+$/.test(a)?
a:u}function X(a){var c=a.flow;var d="answer"!==a.flow?u:a.event.triggerSource||"ENTER_PRESSED_SOURCE";return{flow:c,searchTrigger:d,actionId:W(a),chunks:{length:0,addFromEvent:function(a){var c={event:a,renderingStartAt:new Date,index:this.length};a.index=c.index;return[].push.call(this,c)},getFromEvent:function(a){return this[a.index]},maybeGetLastRendered:function(){for(var a=this.length,c=0;c<a&&this[c].renderingEndAt;c++);return 0===c?null:this[c-1]},markAsRendered:function(a){a=this.getFromEvent(a);
a.renderingEndAt=new Date;return a}},requestStartAt:new Date,requestEndAt:null,answer:{},visibleElems:{length:0,add:function(a){this[a]||[].push.call(this,a)},remove:function(a){delete this[a]}},items:{}}}var O=["text","feedback_chunk"],C={textInputValue:N()},H=!1;document.addEventListener("visibilitychange",S);return{executeAndLogMetrics:function(a,d){d=X(d);var c=C.luggage;c&&(document.removeEventListener("visibilitychange",c.visibilityChangeListenerForLatency),c.answer&&c.answer.observer&&(c.answer.observer.unobserve(c.answer.elem),
document.removeEventListener("visibilitychange",c.answer.visibilityChangeListener)));C.luggage=d;C.textInputValue=N();d={beforeChunk:h(f,d),afterChunkRender:h(D,d),afterFullRender:h(J,d),beforePillRender:h(V,d),afterPillRender:h(M,d)};a(d)},buildContext:function(a,d){return{flow:a,event:d}}}})});e.now("nile-inline-answer-streamer").execute(function(f){f||e.when("A","nile-inline-html-truncator","nile-inline-chunk-renderer","nile-inline-loader-utils","nile-inline-csrf","nile-inline-event-stream-builder",
"nile-inline-uuid-generator","nile-inline-container-manager","nile-inline-search-input-button-controller","nile-inline-state-manager","dpx-rex-nile-inline-display-utils","dpx-rex-nile-inline-widget-instrumentation","dpx-nile-inline-constants","askSearch","ready").register("nile-inline-answer-streamer",function(a,e,f,h,g,d,b,q,F,p,E,l,k,x){function n(a,d){return function(b){a===z&&(f.renderChunk(b,d),p.extend({streamingState:k.streamingState.ANSWER_LOADING}))}}function r(a){return function(){a.close();
p.extend({streamingState:k.streamingState.ERROR});E.displayGenericError()}}function M(d,b){return function(){z=null;d.close();p.getState().streamingState!==k.streamingState.ERROR&&p.extend({streamingState:k.streamingState.ANSWER_RENDERED});b.afterFullRender();h.hideLoader();h.hideTrailingLoader();a.$("#dpx-rex-nile-inline-answer-text-container-sandbox")&&0<a.$("#dpx-rex-nile-inline-answer-text-container-sandbox").length&&a.$("#dpx-rex-nile-inline-answer-text-container-sandbox").empty()}}function K(d,
b){q.clearAnswerContainer();F.showClearButton();b&&(J(),p.extend({streamingState:k.streamingState.ANSWER_LOADING}),e.setIsAnswerExpanded(!1),E.hide("#dpx-rex-nile-inline-default-pills-container"),d&&(a.$("#dpx-rex-nile-search-text-input").val(d),a.$("#dpx-rex-nile-search-text-input").removeAttr("aria-describedby")),h.showLoader(),h.showTrailingLoader(),a.$("#dpx-rex-nile-search-submit-focus-container").focus(),d=a.$("#dpx-rex-nile-loading-response-text").text(),a.$("#dpx-rex-nile-loading-response").append(d))}
function L(a,d,b){a=l.buildContext(d,a);l.executeAndLogMetrics(function(a){b(a)},a)}function I(a){var d=p.getState(),b=d.streamingState===k.streamingState.ERROR;d=(d.streamingState===k.streamingState.ANSWER_RENDERED||d.streamingState===k.streamingState.ANSWER_LOADING)&&a===A;return a?b?!0:d?!1:!0:!1}function J(){G&&G.close()}var G=null,z=null;p.extend({streamingState:k.streamingState.NOT_STARTED});var A;return{streamAnswer:function(a,k,l){var h=a.query;if(I(h)){A=h;var e=p.getState()&&p.getState().blueEnabled;
K(h,e);e&&L(k,l,function(k){var l=b.generateUuid();z=l;var h=g.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),e=d.buildStreamingEndpointCall("/rufus/web/renderedAnswer?");l=n(l,k);var f=r(e);k=M(e,k);e.setErrorCallback(f);e.addEventListener("CONTEXT_CHUNK",l);e.addEventListener("chunk",l);e.addEventListener("close",k);e.startPostStream(a,h,6E4);G=e});x.executeSearch(a.asin,h,e)}},closeStream:J}})});e.now("nile-inline-request-builder").execute(function(f){f||e.when("A","nile-inline-state-manager",
"ready").register("nile-inline-request-builder",function(a,e){function f(a){return(a=(a=(a=a&&a.$target)&&a.closest("[data-action-url]")[0])&&a.dataset)?{actionUrl:a.actionUrl}:{}}function h(a,b,g){var d=e.getState();return Object.assign({query:a,searchSource:b,asin:d.asin,programId:"BLUE_DPX_REX"},g)}function g(){var a=e.getState();return{programId:"BLUE_DPX_REX",conversationId:a&&a.conversationHistoryId||"",turnRequestId:a&&a.requestId||"",gmtTime:(new Date).toISOString()}}return{buildFollowOnPillClickRequest:function(a,
b){return h(a,"BLUE_FOLLOWON_PILL_CLICK_SOURCE",f(b))},buildDefaultPillClickRequest:function(a,b){return h(a,"BLUE_PILL_CLICK_SOURCE",f(b))},buildSearchInputRequest:function(a){return h(a,"LIVE_SEARCH_SOURCE",{})},buildFocusedOutRequest:function(a){return h(a,"BLUE_FOCUS_OUT_SOURCE",{})},buildFeedbackRequest:function(a,b,e){return Object.assign({feedbackType:a,mainFeedback:b},e,g())},buildDetailFeedbackRequest:function(a,b){return Object.assign({feedbackType:"DETAIL_FEEDBACK",detailFeedback:a,freeformFeedback:b},
g())}}})});e.now("dpx-rex-nile-inline-display-utils").execute(function(f){f||e.when("A","nile-inline-loader-utils","ready").register("dpx-rex-nile-inline-display-utils",function(a,e){function f(d){a.$(d).removeClass(g.join(" "))}function h(d){return g.some((b)=>a.$(d).hasClass(b))}var g=["dpx-rex-nile-inline-hidden","nile-inline-hidden","askHidden"];return{show:f,hide:function(d){a.$(d).addClass("dpx-rex-nile-inline-hidden")},isHidden:h,isButtonClickEvent:function(a){var b=a.$event;return 32===b.keyCode?
(b.preventDefault(),!0):13===b.keyCode||"click"===a.type},displayGenericError:function(){h("#dpx-rex-nile-inline-answer-text-container-error")&&(f("#dpx-rex-nile-inline-answer-generic-error"),e.hideLoader(),e.hideTrailingLoader(),f("#dpx-rex-nile-inline-answer-container"),f("#nile-inline-ai-generated-label"),a.$("#dpx-rex-nile-search-text-input").attr("aria-describedby","dpx-rex-nile-inline-answer-generic-error"),a.$("#dpx-rex-nile-inline-answer-generic-error").attr("tabindex","0"),a.$("#dpx-rex-nile-inline-answer-generic-error").focus())}}})});
e.now("nile-inline-container-manager").execute(function(f){f||e.when("A","nile-inline-feedback-actions","dpx-rex-nile-inline-display-utils","nile-inline-state-manager","dpx-nile-inline-constants","nile-inline-loader-utils","ready").register("nile-inline-container-manager",function(a,e,f,h,g,d){var b=a.$;return{clearAnswerContainer:function(){h.extend({streamingState:g.streamingState.NOT_STARTED});h.getState()&&h.getState().streamingState!==g.streamingState.ANSWER_LOADING&&f.hide("#dpx-rex-nile-inline-answer-container");
b("#dpx-rex-nile-inline-answer-text-container").empty();b("#dpx-rex-nile-inline-answer-container-truncating-sandbox").find(".a-truncate-full").empty();b("#dpx-rex-nile-inline-followon-pills-outside-container").empty();e.setFeedbackSent(!1);e.clearFeedbackContainer();b("#dpx-rex-nile-inline-answer-text-container-error").empty();d.hideLoader();d.hideTrailingLoader();f.hide("#dpx-rex-nile-inline-data-container, #dpx-rex-nile-inline-answer-text-container-error, #nile-inline-ai-generated-label, #dpx-rex-nile-inline-answer-generic-error");
b("#dpx-rex-nile-inline-answer-text-container-error, #dpx-rex-nile-inline-answer-generic-error").removeClass("nile-inline-text-container-collapsed-error")}}})});e.now("nile-inline-html-truncator").execute(function(f){f||e.when("A","nile-inline-feedback-actions","nile-inline-loader-utils","nile-inline-state-manager","dpx-nile-inline-constants","dpx-rex-nile-inline-display-utils").register("nile-inline-html-truncator",function(a,e,f,h,g,d){function b(a){var b=a.children();a[0].style.removeProperty("height");
a.find("#"+n(a,"html-truncator-marker")).addClass("dpx-rex-nile-inline-hidden");Array.from(b).forEach((a)=>{a.removeAttribute("aria-hidden")})}function n(a,b){return a[0].id?a[0].id+"-"+b:b}function r(b,d,e){e=n(b,"html-truncator-marker");var g=b.find("#"+e);0===g.length?(d=d.clone(!0),d.removeClass("nile-inline-hidden"),g=a.$(document.createElement("span")),g[0].id=e,g.addClass("nile-inline-truncation-overflow-marker"),g.append(d),b.append(g)):g.removeClass("dpx-rex-nile-inline-hidden");return g}
function p(a,b,d,g,e,l,f,h){f=a.children();g=r(a,g,e);var k=g[0].getBoundingClientRect(),n=document.createRange();n.selectNode(b);var p=n.getBoundingClientRect();n=a[0].getBoundingClientRect();var q=p.height/Math.round(p.height/h);a[0].style.setProperty("height",n.height-(k.bottom-(p.bottom-l*q))+(h-q)/2+"px");a=document.createElement("span");b.nodeType===Node.TEXT_NODE?"BR"===b.tagName?b.before(a):b.after(a):"BR"===b.tagName?b.before(a):b.append(a);b=n.width-g.children()[0].offsetWidth-10;h=a.offsetLeft+
10;0<l&&f[d].setAttribute("aria-hidden","true");0===l&&h<b?g[0].style.setProperty("left",h+"px"):(g[0].style.removeProperty("left"),f[d].setAttribute("aria-hidden","true"));Array.from(f).slice(d+1).forEach((a)=>{a.id!==e&&a.setAttribute("aria-hidden","true")});a.remove()}var E=["absolute","fixed"],l=!1;return{maybeTruncate:function(a,d,g){if(l)return!1;var e=n(a,"html-truncator-marker");var h=n(a,"sandbox");var k=a.parent().find("#"+h);k[0]||(k=a.clone(),k[0].id=h,k.addClass("a-offscreen"),a.after(k));
h=k;k=a.children();h.empty();var r=h[0].getBoundingClientRect().height;h.append("\x3cbr\x3e");r=h[0].getBoundingClientRect().height-r;for(var q=0,x=null,F=0,z=0,A=!1,y=0;y<k.length;y++){var w=0;if(A)break;if(-1===E.indexOf(v.getComputedStyle(k[y]).position)&&k[y].id!==e){var u=k[y].childNodes;h.empty();for(var D=0;D<u.length;D++){var B=u[D];if(B.nodeType!==Node.TEXT_NODE||""!==B.textContent.trim()){var P=B.nodeType===Node.TEXT_NODE?"inline":v.getComputedStyle(B).display;if(P&&P.startsWith("inline")&&
q<=g)if(w=B.cloneNode(!0),w.removeAttribute&&w.removeAttribute("id"),h.append(w),w=Math.round(h[0].offsetHeight/r),q+w===g)x=B,F=y;else if(q+w>g){A=!0;z=x?0:q+w-g;F=(x=x||B)?F:y;break}}}q+=w}}A?(p(a,x,F,d,e,z,h,r),f.hideTrailingLoader()):b(a);return A},expand:b,registerTruncationActions:function(){a.declarative("nile-inline-see-more","click",function(d){b(a.$("#dpx-rex-nile-inline-answer-text-container"));l=!0;h.getState().streamingState===g.streamingState.ANSWER_LOADING&&f.showTrailingLoader()});
a.declarative.create(a.$("#dpx-rex-nile-inline-see-more-action"),"nile-inline-see-more",{})},getIsAnswerExpanded:function(){return l},setIsAnswerExpanded:function(a){l=a}}})});e.now("dpx-nile-inline-constants").execute(function(f){f||e.declare("dpx-nile-inline-constants",{streamingState:{NOT_STARTED:0,ANSWER_LOADING:1,ANSWER_RENDERED:2,ERROR:3}})});e.now("nile-inline-search-input-button-controller").execute(function(f){f||e.when("dpx-rex-nile-inline-display-utils","nile-inline-state-manager","ready").register("nile-inline-search-input-button-controller",
function(a,e){return{showSubmitButton:function(){var f=e.getState()&&e.getState().blueEnabled;a.hide("#dpx-rex-nice-clear-button");f&&a.show("#dpx-rex-nile-submit-button")},showClearButton:function(){e.getState()&&e.getState().blueEnabled&&a.hide("#dpx-rex-nile-submit-button");a.show("#dpx-rex-nice-clear-button")}}})});e.now("nile-inline-dpx-reset-widget").execute(function(f){f||e.when("A","nile-inline-default-pill-actions","nile-inline-container-manager","nile-inline-answer-streamer","nile-inline-html-truncator",
"nile-inline-search-input-button-controller","askSearch").register("nile-inline-dpx-reset-widget",function(a,e,f,h,g,d,b){return function(){h.closeStream();f.clearAnswerContainer();g.setIsAnswerExpanded(!1);e.showDefaultPills();a.$("#dpx-rex-nile-loading-response").empty();a.$("#dpx-rex-nile-search-text-input").val("");a.$("#dpx-rex-nile-search-text-input").removeAttr("aria-describedby");d.showSubmitButton();b.clearSearch()}})});e.now("nile-inline-clear-button-actions").execute(function(f){f||e.when("A",
"nile-inline-dpx-reset-widget","dpx-rex-nile-inline-display-utils").register("nile-inline-clear-button-actions",function(a,e){return{registerClearButtonActions:function(){a.declarative("dpx-rex-nice-clear-button-click","click",function(){e();a.$("#dpx-rex-nile-search-text-input").focus()})}}})});e.now("nile-inline-default-pill-actions").execute(function(f){f||e.when("A","nile-inline-request-builder","nile-inline-answer-streamer","dpx-rex-nile-inline-display-utils","ready").register("nile-inline-default-pill-actions",
function(a,e,f,h){return{registerDefaultPillActions:function(){a.declarative("dpx-rex-nile-inline-pill-clicked","click",function(a){var d=e.buildDefaultPillClickRequest(a.$target[0].value,a);f.streamAnswer(d,a,"pills")})},showDefaultPills:function(){h.show("#dpx-rex-nile-inline-default-pills-container")}}})});e.now("nile-inline-search-input-actions").execute(function(f){f||e.when("A","nile-inline-answer-streamer","nile-inline-search-input-button-controller","nile-inline-request-builder","nile-inline-state-manager",
"nile-inline-dpx-reset-widget","ready").register("nile-inline-search-input-actions",function(a,e,f,h,g,d){function b(a){var b=q("#dpx-rex-nile-search-text-input");b=q.trim(b.val());b="focusout"===a.type?h.buildFocusedOutRequest(b):h.buildSearchInputRequest(b);e.streamAnswer(b,a,"answer")}var q=a.$,n=!1,p=!1;return{registerSearchInputActions:function(){var e=g.getState()&&g.getState().blueEnabled;a.declarative("dpx-rex-submit-button-clicked","click",function(a){Object.assign(a,{triggerSource:"SUBMIT_BUTTON_SOURCE"});
b(a)});a.declarative("dpx-rex-submit-button-clicked","click",function(a){e&&Object.assign(a,{triggerSource:"SUBMIT_BUTTON_SOURCE"});b(a)});e?(q("#dpx-rex-nile-search-text-input").keydown(function(a){if(a.isComposing||229===a.keyCode)p=!0;n=13===a.which}),q("#dpx-rex-nile-search-text-input").focusout(function(a){a=a.relatedTarget;n||q(a).is("input.a-button-input")||"dpx-rex-nile-submit-button-announce"===a.id||q("#dpx-rex-nile-search-text-input").trigger({type:"keyup",which:13,keyCode:13});n=!1}),
q("#dpx-rex-nile-search-text-input").keyup(function(a){""===a.target.value&&d();p?(p=!1,f.showSubmitButton()):13!==a.which?f.showSubmitButton():(q("#dpx-rex-nile-search-text-input").blur(),b(a))})):q("#dpx-rex-nile-search-text-input").keyup(function(a){""===a.target.value&&d();13===a.which&&b(a)})}}})});e.now("nile-inline-feedback-actions").execute(function(f){f||e.when("A","nile-inline-csrf","nile-inline-request-builder","a-popover","dpx-rex-nile-inline-display-utils","a-button","ready").register("nile-inline-feedback-actions",
function(a,e,f,h,g,d){function b(){g.hide("#ask-blue-ai-generated-label");g.show("#ask-feedback-success-text-container");setTimeout(()=>{const b=a.$("#ask-feedback-success-text-container").text().trim();a.$("#ask-feedback-status-announcer").text(b)},500)}function n(d){"THUMBS_UP"===d?(g.hide("#thumbs-up-not-selected"),g.show("#thumbs-up-selected"),a.$("#ask-blue-thumbs-up").attr("aria-disabled","true"),a.$("#ask-blue-thumbs-up").removeAttr("tabindex"),a.$("#ask-blue-thumbs-down").remove(),k.forEach(g.hide),
b()):(g.hide("#thumbs-down-not-selected"),g.show("#thumbs-down-selected"),0<a.$("#a-popover-ask-blue-detail-feedback").length?h.get(a.$("#ask-blue-detail-feedback-action")).show():g.show("#ask-blue-feedback-box"))}function r(){a.$("#ask-blue-feedback-box").remove();h.remove("ask-blue-detail-feedback");k.forEach(g.hide);a.$("#ask-blue-thumbs-up").remove();a.$("#ask-blue-thumbs-down").attr("aria-disabled","true").focus();b()}function p(b){a.$.ajax({url:"/rufus/web/feedback?",data:b,dataType:"json",
type:"POST",timeout:1E4,headers:{"anti-csrftoken-a2z":e.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),"Content-Type":"application/json"}})}function u(){var b=a.$(".ask-blue-feedback-checkbox:checked").map(function(b,d){return a.$(d).val()}).get(),d;a.$("#ask-blue-feedback-option-freetext").is(":checked")&&(d=a.$("#ask-blue-feedback-textbox").val().substring(0,500));p(JSON.stringify(f.buildDetailFeedbackRequest(b,d)))}var l=!1,k=["#thumbs-up-not-selected","#thumbs-down-not-selected","#ask-blue-space-between-thumbs"];
return{registerFeedbackActions:function(){a.declarative("ask-blue-thumbs-up-click","click keydown",function(a){!l&&g.isButtonClickEvent(a)&&(p(JSON.stringify(f.buildFeedbackRequest("MAIN_FEEDBACK","THUMBS_UP",void 0))),n("THUMBS_UP"),l=!0)});a.declarative("ask-blue-thumbs-down-click","click keydown",function(a){!l&&g.isButtonClickEvent(a)&&(p(JSON.stringify(f.buildFeedbackRequest("MAIN_FEEDBACK","THUMBS_DOWN",void 0))),n("THUMBS_DOWN"),l=!0)});a.declarative("ask-blue-feedback-option-click","click",
function(){1<=a.$(".ask-blue-feedback-checkbox:checked").length?(d("#ask-blue-feedback-submit").enable(),a.$("#ask-blue-feedback-submit").prop("disabled",!1)):(d("#ask-blue-feedback-submit").disable(),a.$("#ask-blue-feedback-submit").prop("disabled",!0));a.$("#ask-blue-feedback-option-freetext").is(":checked")?g.show("#ask-blue-feedback-container"):g.hide("#ask-blue-feedback-container")});a.declarative("ask-blue-feedback-close-click","click keydown",function(a){g.isButtonClickEvent(a)&&r()});a.declarative("ask-blue-feedback-cancel-click",
"click",function(){r()});a.declarative("ask-blue-feedback-submit-click","click",function(){u();r()})},setFeedbackSent:function(a){l=a},hideFeedback:function(){g.hide("#dpx-rex-nile-inline-feedback-container")},showFeedback:function(){g.show("#dpx-rex-nile-inline-feedback-container")},clearFeedbackContainer:function(){a.$("#dpx-rex-nile-inline-feedback-container").empty()}}})});e.now("nile-inline-followon-pill-actions").execute(function(f){f||e.when("A","jQuery","nile-inline-request-builder","nile-inline-answer-streamer",
"ready").register("nile-inline-followon-pill-actions",function(a,e,f,h){return{registerFollowOnPillActions:function(){a.declarative("followon-pill-click","click keypress",function(e){var d=f.buildFollowOnPillClickRequest(e.$target[0].value,e);h.streamAnswer(d,e,"pills");d=a.$("#dpx-rex-nice-widget-container");e=d.offset().top;d=e+d.outerHeight();var b=a.$(v).scrollTop(),g=b+a.$(v).height();(d<b||e>g)&&a.$(v).scrollTop(e-(0<a.$(".s-mobile-toolbar-offscreen").length?0:a.$(".s-mobile-toolbar-sticky")?
a.$(".s-mobile-toolbar-sticky").outerHeight():0))})}}})});e.now("nile-inline-widget").execute(function(f){f||e.when("A","jQuery","nile-inline-feedback-actions","nile-inline-default-pill-actions","nile-inline-html-truncator","nile-inline-answer-chunk-handler","nile-inline-followon-pill-actions","dpx-rex-nile-inline-widget-instrumentation","nile-inline-clear-button-actions","nile-inline-search-input-actions","nile-inline-collapse-bottom-sheet","nile-inline-element-prefix-utils","askSearch","askPostQuestion",
"nile-inline-state-manager","ready").register("nile-inline-widget",function(a,e,f,h,g,d,b,q,u,p,v,l,k,x,D){l.setupElementPrefix("dpx-rex");f.registerFeedbackActions();h.registerDefaultPillActions();g.registerTruncationActions();b.registerFollowOnPillActions();u.registerClearButtonActions();v.registerCollapseBottomSheetActions();p.registerSearchInputActions();k.setupExpander();x.registerDeclarativeActions();(a=D.getState())&&a.blueEnabled&&(a=q.buildContext("pills"),q.executeAndLogMetrics(function(a){var b=
{type:"default_pills"};a.beforePillRender(b);var d=e("#dpx-rex-nile-inline-default-pills-container");d=e(d);a.afterPillRender(b,d)},a))})})});
/* ******** */
